export const ERROR = 'ERROR';

export const LOGIN_OLD_USER = 'LOGIN_OLD_USER';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const RESET_EXECUTION = 'RESET EXECUTION';
export const FETCH_MAILS = 'FETCH_MAILS';
export const FETCH_MAILS_REQUEST = 'FETCH_MAILS_REQUEST';
export const FETCH_MAILS_SUCCESS = 'FETCH_MAILS_SUCCESS';
export const FETCH_MAILS_FAILURE = 'FETCH_MAILS_FAILURE';
export const ADD_MAIL = 'ADD_MAIL';
export const START_MAIL = 'START_MAIL';
export const CANCEL_MAIL = 'CANCEL_MAIL';
export const COMPLETE_MAIL = 'COMPLETE_MAIL';
export const DELETE_MAIL = 'DELETE_MAIL';

export const SEARCH_MAILS = 'SEARCH_MAILS';
export const FITLER_MAILS = 'FILTER_MAILS';
export const CATEGORY_MAILS = 'CATEGORY_MAILS';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';