export const MAILS_FETCH_REQUEST = 'MAILS_FETCH_REQUEST';
export const MAILS_FETCH_SUCCESS = 'MAILS_FETCH_SUCCESS';
export const MAILS_FETCH_FAILURE = 'MAILS_FETCH_FAILURE';

export const MAILS_GET = 'MAILS_GET';
export const MAILS_ADD = 'MAILS_ADD';
export const MAILS_START = 'MAILS_START';
export const MAILS_CANCEL = 'MAILS_CANCEL';
export const MAILS_COMPLETE = 'MAILS_COMPLETE';
export const MAILS_DELETE = 'MAILS_DELETE';

export const MAILS_SEARCH = 'MAILS_SEARCH';
export const MAILS_FILTER_SOCIAL = 'MAILS_FILTER_SOCIAL';
export const MAILS_FILTER_CATEGORY = 'MAILS_FILTER_CATEGORY';